#!/bin/dash
# get input
filename=$2
# number of files will be commited
filenum=0 
# number of same files(same filename, same contents)
samenum=0

# check invalid filename which contain new-line character and '-'
# if (echo "$filename"| egrep '[\n]') >/dev/null
# then
#     echo "shrug-commit: incorrect filename:"$filename""
#     echo "filname should not contain new-line character"
#     exit 1
# fi

if (echo "$filename"| egrep '^[-]')>/dev/null
then
    echo "shrug-commit: incorrect filename:"$filename""
    echo "filname should not begin with '-'"
    exit 1
fi
# get the last line of shrug-commit.log, which stored all diaries
lastline=`cat .shrug/.log|tail -1`
# calculate the lines of diaries, it's helpful for append new diary
lastnum=`cat .shrug/.log|wc -l`
num=`echo "$lastnum"|egrep '[0-9]'|sed 's/ //g'`
path=".shrug/index"

# check which file can be commited
for file in $path/*
do  
    # calculate the number of all files
    filenum=`expr $filenum + 1`
    file=`echo "$file"|cut -d '/' -f3`
    if [ -e ".shrug/branch/$file" ]
    then
        diff "$path/$file" ".shrug/branch/$file" >/dev/null
        if [ $? = 0 ]
        then
            # calculate the number of same files
            samenum=`expr $samenun + 1`

        fi
    fi
done

# stderr 'nothing to commit'
if [ $filenum = $samenum ]
then
    echo "nothing to commit"
    exit 1
fi


while true
do
    # create floders for each operation to store datas
    mkdir .shrug/branch/$num
    for file in $path/*
    do
        # copy files from index to branch(current status)
        cp "$file" ".shrug/branch"
        # copy files from index to its floder which sorted by opration times
        cp -fp "$file" ".shrug/branch/$num"
    done
    # print result and how many times it been changed
    echo "Committed as commit $num"
    # append when and what has been copied into shrug-commit.log
    echo "$num $filename" >>'.shrug/.log'
    exit 1
done