#!/bin/dash

for file in $@
do 
    if [ ! -e '.shrug' ]
    then
        echo "shrug-add: error: no .shrug directory containing shrug repository exists"
        exit 1
    fi
    # check invalid filename
    if [ ! -e $file ]
    then
        echo "shrug-add: error: can not open '$file'"
        exit 1
    fi
    if ((echo "$file" | egrep -v '[a-zA-Z0-9\.\-\_]')||(echo "$file"|egrep -v '^[a-zA-Z0-9]')) >/dev/null
    then 
        echo "shrug-add:incorrect filename: $file"
        echo "filename should start with [a-zA-Z0-9] and only contain '.', '-' ,'_'  "
        exit 1
    else
        # copy valid file to index 
        cp "$file" ".shrug/index/$file"
    fi
done
