#!/bin/dash
#floder
path=`echo "$@"|cut -d ' ' -f2|cut -d ':' -f1`
#filename
filename=`echo "$@"|cut -d ' ' -f2|cut -d ':' -f2`

#check the path invalid or not
if ( echo "$path"|egrep '[0-9]' )>/dev/null
then
    if [ ! -e ".shrug/branch/$path" ]
    then
        echo "shrug-show: error: unknown commit '$path'"
        exit 1
    fi
    if [ -e ".shrug/branch/$path/$filename" ]
    then  
        #print output
        output=`cat ".shrug/branch/$path/$filename"`
        echo "$output"
        exit 0
    else
         echo "shrug-show: error: '$filename' not found in commit $path"
         exit 1
    fi
else
    if [  -e ".shrug/index/$filename" ]
    then
        output=`cat ".shrug/index/$filename"`
        echo "$output"
        exit 0
    else
        echo "shrug-show: error: '$filename' not found in index"
        exit 1
    fi
fi

