# Makefile generated at Tue  4 Aug 15:49:26 AEST 2020

CC = gcc
CFLAGS = -Wall -g

easymain:	world.o	easymain.o	graphics.o
	$(CC) $(CFLAGS) -o $@ world.o easymain.o graphics.o

	world.o:HASH(0x1065090)
world.o:	world.h	world.c
	easymain.o:HASH(0xf65d90)
easymain.o:	easymain.c	graphics.h	world.h
	graphics.o:HASH(0x1065060)
graphics.o:	graphics.c	world.h	graphics.h
