#!/bin/dash

# echo $#
indexpath=".shrug/index"
# input
input=$@
# shrug-rm a.txt
if [ $# = 1 ]
then
    for file in *
    do
        if ( echo "$file"| egrep -v '*shrug*'| egrep -v 'test*'|egrep -v 'diary.txt')>/dev/null
        then
            for f in $file
            do  
                if $f in $input
                then 
                    if [ -e "$indexpath/$f" ]
                    then
                        diff "$f" "$indexpath/$f">/dev/null
                        if [ $? = 0 ]
                        then
                            rm $f
                            rm "$indexpath/$f"
                        else
                            echo "'$f' in repository is different to working file"
                        fi
                    fi
                fi
            done
        fi
    done

fi

if [ $# = 2 ]
then
    # shrug-rm --cached a.txt
    if [ $1 -e '--cached' ]
    then
        for file in *
        do
            if ( echo "$file"| egrep -v '*shrug*'| egrep -v 'test*'|egrep -v 'diary.txt')>/dev/null
            then
                for f in $file
                do  
                    if $f in $input
                    then 
                        if [ -e "$indexpath/$f" ]
                        then
                            diff "$f" "$indexpath/$f">/dev/null
                            if [ $? = 0 ]
                            then
                                rm "$indexpath/$f"
                            fi
                        fi
                    fi
                done
            fi
        done
    else
        # shrug-rm ----force a.txt
        if [ $1 -e '--force' ]
        then
            for file in *
            do
                if ( echo "$file"| egrep -v '*shrug*'| egrep -v 'test*'|egrep -v 'diary.txt')>/dev/null
                then
                    for f in $file
                    do  
                        if $ in $input
                        then
                            if [ -e "$indexpath/$f" ]
                            then
                                rm $f
                                rm "$indexpath/$f"
                            fi
                        fi
                    done
                fi
            done
        fi
    fi

fi

if [ $# = 3 ]
then
    for file in *
    do
        if ( echo "$file"| egrep -v '*shrug*'| egrep -v 'test*'|egrep -v 'diary.txt')>/dev/null
        then
            for f in $file
            do  
                if [ -e "$indexpath/$f" ]
                then
                    diff "$f" "$indexpath/$f">/dev/null
                    if [ $? = 1 ]
                    then
                        rm "$indexpath/$f"
                    fi
                fi
            done
        fi
    done

fi


