#!/bin/dash

# edit by Jie CHEN, z5236591
# started at 19:30 09/07/20
# modified at 23:00 09/07/20: get error output from autotest

#floder
path=`echo "$@"|cut -d ' ' -f2|cut -d ':' -f1`
#filename
filename=`echo "$@"|cut -d ' ' -f2|cut -d ':' -f2`

#check the path invalid or not
if ( echo "$path"|egrep '[0-9]' )>/dev/null
then
    # check shrug-show 0:a: the 0 exists or not
    if [ ! -e ".shrug/branch/$path" ]
    then
        echo "shrug-show: error: unknown commit '$path'"
        exit 1
    fi
    # check shrug-show 0:a: the 0:a exists or not
    if [ -e ".shrug/branch/$path/$filename" ]
    then  
        #print output
        output=`cat ".shrug/branch/$path/$filename"`
        echo "$output"
        exit 0
    else
         echo "shrug-show: error: '$filename' not found in commit $path"
         exit 1
    fi
else
    # check shrug-show :a
    if [  -e ".shrug/index/$filename" ]
    then
        output=`cat ".shrug/index/$filename"`
        echo "$output"
        exit 0
    else
        echo "shrug-show: error: '$filename' not found in index"
        exit 1
    fi
fi

