#!/bin/dash

# edit by Jie CHEN, z5236591
# started at 17:30 09/07/20
# 1st modified in 19:00 09/07/20: add commit floder in shrug-commit: 0, 1, 2
# 2nd modified in 10:00 10/07/20: add error messages into shrug-commit
# 3rd modified in 13:00 10/07/20: add 'nothing to commit'
# 4th modified in 14:30 10/07/20: add fuction -a


if [ "$1" = '-m' ]
then
# get input
filename=$2
else
    if [ "$1" = '-a' ] 
    then
        # commit name
        filename=$3
        for file in *
        do
            # get files in current directory
            if ( echo "$file"| egrep -v '*shrug*'| egrep -v 'test*'|egrep -v 'diary.txt')>/dev/null
            then
                for f in $file
                do  
                    # check the file in index or not
                    if [ -e ".shrug/index/$f" ]
                    then
                        if [ ! -e '.shrug' ]
                        then
                            echo "shrug-add: error: no .shrug directory containing shrug repository exists"
                            exit 1
                        fi
                        # check invalid filename
                        # if [ ! -e $f ]
                        # then
                        #     echo "shrug-add: error: can not open '$f'"
                        #     exit 1
                        # fi
                        if ((echo "$f" | egrep -v '[a-zA-Z0-9\.\-\_]')||(echo "$f"|egrep -v '^[a-zA-Z0-9]')) >/dev/null
                        then 
                            echo "shrug-add:incorrect filename: $f"
                            echo "filename should start with [a-zA-Z0-9] and only contain '.', '-' ,'_'  "
                            exit 1
                        else
                            # copy valid file to index 
                            cp "$f" ".shrug/index/$f"
                        fi
                    fi
                done
            fi
        done
    fi
fi
# number of files will be commited
filenum=0 
# number of same files(same filename, same contents)
samenum=0

# check invalid filename which contain new-line character and '-'
# if (echo "$filename"| egrep '[\n]') >/dev/null
# then
#     echo "shrug-commit: incorrect filename:"$filename""
#     echo "filname should not contain new-line character"
#     exit 1
# fi

if (echo "$filename"| egrep '^[-]')>/dev/null
then
    echo "shrug-commit: incorrect filename:"$filename""
    echo "filname should not begin with '-'"
    exit 1
fi
# get the last line of shrug-commit.log, which stored all diaries
lastline=`cat .shrug/.log|tail -1`
# calculate the lines of diaries, it's helpful for append new diary
lastnum=`cat .shrug/.log|wc -l`
num=`echo "$lastnum"|egrep '[0-9]'|sed 's/ //g'`
path=".shrug/index"

# check which file can be commited
for file in $path/*
do  
    # calculate the number of all files
    filenum=`expr $filenum + 1`
    file=`echo "$file"|cut -d '/' -f3`
    if [ -e ".shrug/branch/$file" ]
    then
        diff "$path/$file" ".shrug/branch/$file" >/dev/null
        if [ $? = 0 ]
        then
            # calculate the number of same files
            samenum=`expr $samenun + 1`

        fi
    fi
done

# stderr 'nothing to commit'
if [ $filenum = $samenum ]
then
    echo "nothing to commit"
    exit 1
fi


while true
do
    # create floders for each operation to store datas
    mkdir .shrug/branch/$num
    for file in $path/*
    do
        # copy files from index to branch(current status)
        cp "$file" ".shrug/branch"
        # copy files from index to its floder which sorted by opration times
        cp -fp "$file" ".shrug/branch/$num"
    done
    # print result and how many times it been changed
    echo "Committed as commit $num"
    # append when and what has been copied into shrug-commit.log
    echo "$num $filename" >>'.shrug/.log'
    exit 1
done